color0 #212226
color1 #f92672
color2 #a6e22e
color3 #f4bf75
color4 #66d9ef
color5 #ae81ff
color6 #a1efe4
color7 #e1e2e5
color8 #75715e
color9 #f92672
color10 #a6e22e
color11 #f4bf75
color12 #66d9ef
color13 #ae81ff
color14 #a1efe4
color15 #f9f8f5

cursor                #bfc0de
cursor_text_color     #212226
background            #212226
foreground            #e1e2e5
selection_foreground  #debfbf
selection_background  #373940
active_border_color   #bfc0de
inactive_border_color #2c2e33
url_color             #bfc0de

active_tab_foreground   #262626
active_tab_background   #bfc0de
inactive_tab_foreground #e1e2e5
inactive_tab_background #2c2e33
cursor_trail_color      #e1e2e5
